language: python
notifications:
  email: false
python:
  - "2.7"
install:
  - "sudo apt-get install -y"
  - "easy_install -U setuptools"
  - "pip install ."
  - "pip install -r requirements.txt"
  - "pip install -r test_requirements.txt"
script:
  - py.test test --doctest-modules -v --cov pyconsensus --cov-report term-missing
after_success:
  - coveralls